apiVersion: v1
kind: Service
metadata:
  name: compute-pi-svc
  namespace: multi
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    name: compute-pi-pod
  type: NodePort